/* This file is generated by Ziggy. */
declare module "ziggy-js" {
  interface RouteList {
    index: [
      {
        name: "uri";
        required: true;
      },
    ];
    "storage.local": [
      {
        name: "path";
        required: true;
      },
    ];
  }
}
export {};
